### ISSUE TITLE
About chinese

### ISSUE THREAD

**Issue by Soulscb** [openai/CLIP#192] opened 2021-12-03 02:17 UTC
now i test with chinese text and image to calculate cosine similarity , i find it very terrible, so it can support chinese?

**Comment by jongwook** [comment] 2021-12-03 03:20
Closing as duplicate of #142 and #7.

**Closed by jongwook** 2021-12-03 03:20 UTC

**Comment by yangapku** [comment] 2022-07-15 02:53
Hi, maybe you can refer to this repo! https://github.com/OFA-Sys/Chinese-CLIP
