### ISSUE TITLE
Training Dataset

### ISSUE THREAD

**Issue by iremonur** [openai/CLIP#178] opened 2021-11-10 21:20 UTC
Hi, I would like to reach the dataset on which the CLIP was trained. In the paper, it is said that a new dataset was created that contains 400 million image-text pairs but where it can be found was not given. Does anyone know how to access the training dataset?
I would be very glad if you help me with this.

**Comment by jongwook** [comment] 2021-11-16 01:55
Closing as duplicate of #127

**Closed by jongwook** 2021-11-16 01:55 UTC
